name: "Checks"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup NodeJS"
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: ./node_modules/
          key: node-modules-${{ runner.os }}
      - name: "Run"
        run: npm run test
